### The `end` operator

This thing is really useful. It grabs the last element from the specified dimension

For example, here I grab the last element from the first row

In [1]:
x = reshape(1:12, [4,3])
x(1,end)


x =

     1     5     9
     2     6    10
     3     7    11
     4     8    12


ans =

     9




Now, I will grab the last element from the first column:

In [2]:
x
x(end,1)


x =

     1     5     9
     2     6    10
     3     7    11
     4     8    12


ans =

     4




The end operator can be used with offsets as well.

Here I grab the second last element of the first column:

In [3]:
x
x(end-1,1)


x =

     1     5     9
     2     6    10
     3     7    11
     4     8    12


ans =

     3




Let's use the `end` operator with the everthing (`:`) operator.

We'll select everthing from the last colummn:

In [4]:
x
x(:,end)


x =

     1     5     9
     2     6    10
     3     7    11
     4     8    12


ans =

     9
    10
    11
    12




And here select everything (all columns) from the second last row:

In [5]:
x
x(end-1,:)


x =

     1     5     9
     2     6    10
     3     7    11
     4     8    12


ans =

     3     7    11




Final thoughts:

The `end` operator is really helpful, but is limited - for example it cannot be used in `for` structures later on.