### Multi-Dimensional Arrays
More than just vectors.

So here, let's take a look at creating multi-dimensional arrays.

We can start by using the tools we already have:

In [1]:
x = [1 2 3; 4 5 6]
y = [[1;2], [3;4], [5;6]]



x =

     1     2     3
     4     5     6


y =

     1     3     5
     2     4     6




You can do fancy insertion and transposition

In [2]:
x = [1:5];
y = [x; x; x;]
z = [x', x', x']


y =

     1     2     3     4     5
     1     2     3     4     5
     1     2     3     4     5


z =

     1     1     1
     2     2     2
     3     3     3
     4     4     4
     5     5     5




In [3]:
x = zeros(2,4)
y = ones(4,2)
z = rand(1,5)


x =

     0     0     0     0
     0     0     0     0


y =

     1     1
     1     1
     1     1
     1     1


z =

    0.8147    0.9058    0.1270    0.9134    0.6324




Sometimes you want to reshape your data into a particular size

In [4]:
x = [1:10];
y = reshape(x, [2,5])
z = reshape(x, [5,2])


y =

     1     3     5     7     9
     2     4     6     8    10


z =

     1     6
     2     7
     3     8
     4     9
     5    10




If you want to do something really whacky you can! There are some important things to remember:

 * matrix access / shape commands call the nRows dimension first
 * matrix access / shape commands call the nCols dimension second
 * other dimensions are then called in order
 * the everything operator returns your matrix as  single column list
 
 Let's take a look at a complicated transformation

In [5]:
w   = [1:18];
x   = reshape( w, [9, 2])
x_1 = x'
y   = x_1(:)
z   = reshape(y, [3, 3, 2])


x =

     1    10
     2    11
     3    12
     4    13
     5    14
     6    15
     7    16
     8    17
     9    18


x_1 =

     1     2     3     4     5     6     7     8     9
    10    11    12    13    14    15    16    17    18


y =

     1
    10
     2
    11
     3
    12
     4
    13
     5
    14
     6
    15
     7
    16
     8
    17
     9
    18


z(:,:,1) =

     1    11     4
    10     3    13
     2    12     5


z(:,:,2) =

    14     7    17
     6    16     9
    15     8    18




There is a predictable order to the structure of z. Further exposure will make it more intuitive.