### Accessing Individual Data Points Within Your Arrays

It's actually quite easyto get sub elements. Let's get started.

Here are the key points:
* MATLAB uses 1 based indices.
* Unlike python, MATLAB uses brackets `[` and `]` to _construct_ matrices and  _parentheses_ `(` and `)` to access data

In [1]:
x = [1:3]
x(2)


x =

     1     2     3


ans =

     2




An index of zero or negative one (or NaN or Inf for any non-integer that matter!) causes issues

In [2]:
x = 1:5;
x(-1)

Subscript indices must either be real positive integers or logicals.



In [3]:
x(0)

Subscript indices must either be real positive integers or logicals.



In [4]:
x(NaN)

Subscript indices must either be real positive integers or logicals.



In [5]:
x(Inf)

Subscript indices must either be real positive integers or logicals.



In [6]:
x(1.2)

Subscript indices must either be real positive integers or logicals.



There are some things that do work that you might not expect. For example, 

In [7]:
x = [1:100];
x('')
x([])
x('0')


ans =

     []


ans =

     []


ans =

    48




Which tells us that if we access an empty matrix, we get an empty matrix, and that `char`'s are treated as `int`s for access purposes, since

In [8]:
double('0')


ans =

    48




and for that matter, 

In [9]:
double('abcde')


ans =

    97    98    99   100   101




Let's go back to things that work, though.
In this example, we are going to access scalar elements of a 2-D array. Note that MATLAB iterates by columns. 

In [10]:
x = reshape(1:10, [5,2])'


x =

     1     2     3     4     5
     6     7     8     9    10




In [11]:
x(1)
x(2)
x(3)

x(9)
x(10)


ans =

     1


ans =

     6


ans =

     2


ans =

     5


ans =

    10




Which is to say that for scalar acess, MATLAB views x as this:

In [12]:
x(:)


ans =

     1
     6
     2
     7
     3
     8
     4
     9
     5
    10




Which we saw before.

You can also access by row or by column. Here we select from row 1

In [13]:
x = reshape(1:10, [5,2])'

x(1,2)
x(1,3)


x =

     1     2     3     4     5
     6     7     8     9    10


ans =

     2


ans =

     3




And here I select from column 4

In [14]:
 x(1,4)
 x(2,4)


ans =

     4


ans =

     9


